### ISSUE TITLE
Issue from Jean 5

### ISSUE THREAD

**Issue by knmc** [apache/openoffice-docs#63]
Page 178, the  blank page, should be removed.

**Comment by knmc** [comment]
AOO41GS7(Chapter6).

**Comment by DiGro** [comment]
Fixed in AOO41GS7_20220709

**Comment by knmc** [comment]
Dick; I still see the blank page at the end of AOO41GS7_20220709. Was this an oversight? If so, I will delete it in my working directory and close this.

**Comment by DiGro** [comment]
Keith,

sorry for coming bacj so late. Missed this one a bit.
I jusrt checked my file AOO41GS7_20220709 and there is no blank page anymore. Text is approx half way last page.

I suppose you already fixed it, if it was there. I'll close the issue
